src/views/admin.py
# -*- coding: utf8 -*-

from flask import Blueprint, g, render_template
from utils.tool import admin_login_required, logger


admin_blueprint = Blueprint("admin", __name__)

@admin_blueprint.route("/")
@admin_login_required
def index():
    return render_template("admin/index.html")

@admin_blueprint.route("/blogManager/")
@admin_login_required
def blog():
    return render_template("admin/blog.html")

@admin_blueprint.route("/systemConf/")
@admin_login_required
def system():
    return render_template("admin/system.html")


src/views/front.py
# -*- coding: utf8 -*-

import requests, datetime, SpliceURL
from urlparse import urljoin
from werkzeug.contrib.atom import AtomFeed
from flask import Blueprint, g, render_template, request, redirect, url_for, make_response, abort
from utils.tool import login_required, logger, BaiduActivePush


front_blueprint = Blueprint("front", __name__)

@front_blueprint.route("/")
def index():
    return render_template("front/blogIndex.html")

@front_blueprint.route('/blog/<int:bid>.html')
def blogShow(bid):
    data = g.api.blog_get_id(bid).get("data")
    if data:
        BaiduActivePushResult = False
        if g.plugins['BaiduActivePush']['enable'] in ("true", "True", True):
            original = True if data.get("sources") == "原创" else False
            BaiduActivePushResult = True if BaiduActivePush(request.url, original=original).get("success") == 1 else False
        return render_template("front/blogShow.html", blogId=bid, data=data, BaiduActivePushResult=BaiduActivePushResult)
    else:
        return abort(404)

@front_blueprint.route("/blog/write/")
@login_required
def blogWrite():
    return render_template("front/blogWrite.html")

@front_blueprint.route("/blog/edit/")
@login_required
def blogEdit():
    blogId = request.args.get("blogId")
    if blogId:
        data = g.api.blog_get_id(blogId).get("data")
        if data:
            if g.username == data.get("author") or g.username in g.api.user_get_admins().get("data"):
                return render_template("front/blogEdit.html", blogId=blogId, data=data)
        return abort(404)

@front_blueprint.route("/blog/resource/")
def blogResource():
    return render_template("front/blogResource.html")

@front_blueprint.route("/user/<user>/")
def userHome(user=None):
    logger.debug(user)
    return render_template("front/userHome.html", user=user)

@front_blueprint.route("/user/ChangeAvater/")
@login_required
def userChangeAvater():
    return render_template("front/userChangeAvater.html")

@front_blueprint.route("/user/ChangePassword/")
@login_required
def userChangePassword():
    return render_template("front/userChangePassword.html")

@front_blueprint.route("/user/ChangeCover/")
@login_required
def userChangeCover():
    return render_template("front/userChangeCover.html")

@front_blueprint.route("/robots.txt")
def robots():
    return """
User-agent: *
Disallow: 
Sitemap: http://www.saintic.com/sitemap.xml
    """
##
@front_blueprint.route("/sitemap.xml")
def sitemap():
    resp = make_response(render_template("public/sitemap.xml", data=get_index_list()))
    resp.headers["Content-Type"] = "application/xml"    
    return resp

@front_blueprint.route("/feed/")
def feed():
    data = g.api.blog_get_all(limit=10).get("data")
    feed = AtomFeed(u'清水蓝天博客源', feed_url=request.url, url=request.url_root, subtitle="From the latest article in EauDouce")
    for article in data:
        updated = article['update_time'][:10] if article['update_time'] else article['create_time'][:10]
        feed.add(article['title'], unicode(article['content']),
                 content_type='html',
                 author=article['author'],
                 id=article['id'],
                 url=urljoin(request.url_root, url_for(".blogShow", bid=article['id'])),
                 updated=datetime.datetime.strptime(updated, "%Y-%m-%d"),
                 published=datetime.datetime.strptime(article['create_time'][:10], "%Y-%m-%d"))
    return feed.get_response()

src/templates/base/admin.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}后台管理{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin/css/common.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin/css/main.css') }}"/>
    <script type="text/javascript" src="{{ url_for('static', filename='admin/js/libs/modernizr.min.js') }}"></script>
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon" />
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="shortcut icon" type="image/x-icon" />
</head>
<body>
<div class="topbar-wrap white">
    <div class="topbar-inner clearfix">
        <div class="topbar-logo-wrap clearfix">
            <h1 class="topbar-logo none"><a href="index.html" class="navbar-brand">后台管理</a></h1>
            <ul class="navbar-list clearfix">
                <li><a class="on" href="{{ url_for('admin.index') }}">首页</a></li>
                <li><a href="{{ url_for('front.index') }}" target="_blank">网站首页</a></li>
            </ul>
        </div>
        <div class="top-info-wrap">
            <ul class="top-info-list clearfix">
                <li><a href="{{ url_for('front.userHome', user=g.username) }}">欢迎您管理员</a></li>
                <li><a href="{{ url_for('logout') }}">退出</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container clearfix">
    <div class="sidebar-wrap">
        <div class="sidebar-content">
            <ul class="sidebar-list">
                <li>
                    <i class="icon-font">&#xe018;</i>系统管理
                    <ul class="sub-menu">
                        <li><a href="{{ url_for('admin.index') }}"><i class="icon-font">&#xe022;</i>系统信息</a></li>
                        <li><a href="{{ url_for('admin.system') }}"><i class="icon-font">&#xe017;</i>系统设置</a></li>
                    </ul>
                </li>
                <li>
                    <i class="icon-font">&#xe003;</i>博客管理
                    <ul class="sub-menu">
                        <li><a href="{{ url_for('admin.blog') }}"><i class="icon-font">&#xe005;</i>博文管理</a></li>
                        <li><a href="design.html"><i class="icon-font">&#xe006;</i>分类管理</a></li>
                        <li><a href="design.html"><i class="icon-font">&#xe052;</i>友情链接</a></li>
                        <li><a href="design.html"><i class="icon-font">&#xe033;</i>广告管理</a></li>
                        <li><a href="http://changyan.kuaizhan.com/overview"><i class="icon-font">&#xe012;</i>评论管理</a></li>
                    </ul>
                </li>
                <li>
                    <i class="icon-font">&#xe018;</i>用户管理
                    <ul class="sub-menu">
                        <li><a href="#"><i class="icon-font">&#xe037;</i>用户管理</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    {% block sidebar %}{% endblock %}
</div>
</body>
</html>

src/templates/base/micro.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <title>{% block title %}{% endblock %} | SaintIC EauDouce - 清水蓝天博客</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="博客,blog,Interest,IT">
    <meta name="description" content="Linux,NoSQL,DevOps,python,Docker,redis,memcache,MongoDB,LVS,HA,LB,puppet,ansible,func,Cloud,BigData">
    <link rel="canonical" href="https://www.saintic.com/">
    <!-- 引入 Bootstrap -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- HTML5 Shim 和 Respond.js 用于让 IE8 支持 HTML5元素和媒体查询 -->
    <!-- 注意： 如果通过 file://  引入 Respond.js 文件，则该文件无法起效果 -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="icon" type="image/x-icon" />
    <link href="{{ url_for('static', filename='img/favicon.ico') }}" rel="shortcut icon" type="image/x-icon" />
    {% block head %}{% endblock %}
</head>
<body>

<div class="container">

    <div class="header">
    <br />
    {% block container %}{% endblock %}
    </br>
    </br>
</div>

<script src="{{ url_for('static', filename='js/jquery-3.1.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='layer/layer.js') }}"></script>
{% block script %}{% endblock %}
</body>
</html>